### ISSUE TITLE
Having the precision being represented as a Constraint

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#10]
I think it would be useful to have `Type.applicableConstraints()` to include a Constraint representing the precision, as we have for the lower and upper bounds of `Number`. To me it seems a constraint because it limits the acceptable values that can be assigned to an instance of that type.

For example if I have `number{2}` I should not assign to it `1.234`

**Comment by markusvoelter** [comment]
Can you write the concrete code you want not to work? The above example seems strange because you cannot assign to 1.234 in any case.

**Comment by ftomassetti** [comment]
![selection_427](https://cloud.githubusercontent.com/assets/439078/20381873/a61720c0-aca9-11e6-8c54-76133bec2de1.png)

Maybe I am missing something but here it seems to me that I can assign a number with 4 decimal digits to `number{2}`.

I was expecting the system to complain when trying to assign something with more than 2 decimal digits to a `number{2}`.

Given my assumptions that a `number{2}` would have to accept only numbers with 2 or less decimal digits but not number with more digits I thought of it as a constraint that could be listed among the `Type.applicableConstraints()`

**Comment by markusvoelter** [comment]
Fixed. For assignment, the precision has to match now.

**Comment by ftomassetti** [comment]
What about the original point:

> I think it would be useful to have Type.applicableConstraints() to include a Constraint representing the precision, as we have for the lower and upper bounds of Number.

Is it something that makes sense to you or not?

**Comment by markusvoelter** [comment]
I cannot list it under the constraints because, technically, it is not a contraint. But please give us one or two more days; we are refactoring a bunch of things in the type system internally; you should then be able to access the type declaration itself, which contains the precision.

**Comment by ftomassetti** [comment]
Yes, for the min and max I am doing that anyway: going to the definition and verifying if it is a min or max specified, I will do the same for the number of digits

**Comment by markusvoelter** [comment]
So then what is the problem?

**Comment by ftomassetti** [comment]
No problem, it was just a suggestion: it seemed to me a constraint so I thought would make sense to open a ticket for discussing it. Then we started talking about the issue with assignments and lost track of it so I wanted to be sure we had a decision on that. If the decision is "we don't need it", it is not a problem for me.

**Comment by markusvoelter** [comment]
Ok. What we will do is to make sure we don't "loose" type information by "jumping over" typedefs. Once we have done that, it is easy to collect all constraints and the original number type. Then you have everything available in a declarative way.
