### ISSUE TITLE
Make default substitute menu for Component configurable

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#102]
### Current default substitution menu

The current default substitution menu of our component looks like this: 
![grafik](https://user-images.githubusercontent.com/16648247/34158127-7e8d9fee-e4c4-11e7-841f-027b566b2abe.png)
It shows the menu entries created by the grammar cells and the default menu for the component. It would also show the kinds (inside wrap substitute actions) which are not implemented in the iets.os framework.
 
### Substitution menu with *empty* default substitute menu for Component
![grafik](https://user-images.githubusercontent.com/16648247/34159623-34fa3ecc-e4ca-11e7-99d2-7fdb53ab66d9.png)
Here only the menu entries, contributed by the grammar cells are visible.

In some customer porject we are customizing the editor for an component with the help of grammar cells and would like to avoid the **default substitute menu for Component** to be part of the substitute menu. 

To avoid this it would be great to be able to customize a default substitute menu of a concept from any other language **OR** if we could just add an empty default substitute menu for Component.

**Comment by alexanderpann** [comment]
Some small customization can now also be done through https://github.com/IETS3/iets3.opensource/pull/715 and the new interface IPreferredProposalContext.
