### ISSUE TITLE
Port has no typesystem type

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#107]
Port  currently implements IContextTypeProvider but does not have any typesystem type wich is required in the IConceptSpecificAttribute contstraint. 

Therefore a fallback implementation is always needed inside the constraint if the **IConceptSpecificAttribute.getTypedContextNode().type** is empty.

**Comment by coolya** [comment]
Obsolet?

**Comment by alexanderpann** [comment]
Closing this ticket because the port has a type and this issue seems obsolete. Feel free to reopen if the problem still exists.
