### ISSUE TITLE
Clean up executor logic for iets3 tests

### ISSUE THREAD

**Issue by szabta89** [IETS3/iets3.opensource#109]
Currently, the built in executor is also applicable to iets3 test suites. 
This is a problem because we also have a custom executor that is visible in the right click menu. 
Try to consolidate this and see how this can be unified.

**Comment by arimer** [comment]
@szabta89 any interest in fixing this ticket 😅 ?

**Comment by alexanderpann** [comment]
Let's close this ticket. I don't understand it and it is probably obsolete.
