### ISSUE TITLE
Having declarative constraints

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#11]
In my opinion it would be useful to have declarative constraints returned by `Type.applicableConstraints()`. Currently they return an expression, which I could evaluate but I cannot easily translate in other contexts.

For example I could want to verify that constraint on JS. If the constraint was declarative (e.g., `LowerBound(10)`) I could do easily.

**Comment by markusvoelter** [comment]
You can have an arbitrary constraint on the type, an arbitrary boolean expression. I cannot return something declarative in this case. If you want to know the range, then you can get that from the type declaration if it is a number type (only there the range makes sense in the first place).

**Comment by ftomassetti** [comment]
Ok, I added ad-hoc logic to derive declarative constraints for this. Thanks.
