### ISSUE TITLE
Typesystem of lists does not reflect lower bound

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#1114]
Crosscheck if this this a bug or idended behaviour. 

<img width="831" alt="grafik" src="https://github.com/user-attachments/assets/1b131936-c1e5-4e7f-bab4-52fd99e88715">

**Expected behaviour**
 The outer list has a lower bound of 0 and therefore it is not mandatory that the list contains any entries. The error should not be there.

**Comment by alexanderpann** [comment]
The error message is still correct since you need to set the type for empty list literal yourself but the derived list size should be 0.
