### ISSUE TITLE
#1099 undid #1097 -- automerge issue?

### ISSUE THREAD

**Issue by enikao** [IETS3/iets3.opensource#1140]
#1099 undid #1097 -- `selectAllTraceNodeInCurrentTrace.updateInBackground` is again `true`.

Is this an issue with auto-merge?

**Comment by enikao** [comment]
@alexanderpann This was your merge commit

**Comment by alexanderpann** [comment]
Fixed in https://github.com/IETS3/iets3.opensource/pull/1141
