### ISSUE TITLE
Automerge in pipeline broken

### ISSUE THREAD

**Issue by enikao** [IETS3/iets3.opensource#1156]
I'm looking at the current HEAD of `maintenance/mps2023.2`, `67eade33d6145b551dfcf867240442edb65cc65d`.

It has none of my changes in #1113, I can't figure out where they got lost. At the time this PR was merged, `master` was still on MPS 2023.2.

**Comment by enikao** [comment]
They still seem to exist on `master`.

**Comment by alexanderpann** [comment]
I am very sorry that this happened (again), we never had those problems before. I feel like there must have been a history rewrite, I can't figure it out either. It looks like the commits never existed on the maintenance/mps2023.2 branch.
