### ISSUE TITLE
Outdated MPS version in pom.xml

### ISSUE THREAD

**Issue by stephaneberle9** [IETS3/iets3.opensource#120]
https://projects.itemis.de/nexus/service/local/repo_groups/OS/content/org/iets3/opensource/0.1.2700.ba9fa50/opensource-0.1.2700.ba9fa50.pom

Expected MPS version: com.jetbrains:mps:2017.3.5
Actual MPS version: com.jetbrains:mps:2017.3.2

**Comment by coolya** [comment]
fixed with #121
