### ISSUE TITLE
Cant build editor models from IDE after migration to 2018.1

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#127]
Editor models of the following languages *cannot* be build currently from IDE:

```
org.iets3.components.core
org.iets3.core.expr.lookup
org.iets3.core.expr.math
org.iets3.core.expr.typetags
org.iets3.core.expr.typetags.units
org.iets3.core.expr.util
org.iets3.core.expr.base
org.iets3.core.expr.collections
org.iets3.core.expr.lambda
org.iets3.core.expr.repl
org.iets3.core.expr.simpleTypes
org.iets3.core.expr.tests
org.iets3.core.expr.toplevel
org.iets3.core.expr.mutable
org.iets3.core.expr.process
org.iets3.core.expr.statemachines
org.iets3.glossary
org.iets3.req.core
```
All of them are throwing the following exception: 

`broken reference 'baseMethodDeclaration' in [actualArgument] LocalMethodCall null[4484200617054098948] in org.iets3.components.core.editor@5_0 (target model is null)`

I think in *ALL* this cases an "optimize imports" was performed, which removed dependnecies to some grammar cell related languages.

**Comment by coolya** [comment]
Shutdown MPS, do a got clean and then gradle setup with refresh dependencies. Works for me.

**Comment by arimer** [comment]
@coolya 

Ok, most of the stuff works now, but I still can't build the editor model of `org.iets3.components.core`. Also the components editor is *not* build during command line build. 

I attached the exception which is thrown when generating the editor model: 
[GenerationFailureException.txt](https://github.com/IETS3/iets3.opensource/files/1918992/GenerationFailureException.txt)

**Comment by arimer** [comment]
Works with most current version of MPS:

Build: 181.1168
Released: April 5, 2018
