### ISSUE TITLE
Sort out the table intervals

### ISSUE THREAD

**Issue by saadbinabid1** [IETS3/iets3.opensource#14]
At present the table intervals (both increasing/decreasing) have no particular order of values. But we would like to have values either in ascending or descending order.

**Requirement:**
The user can sort the intervals (increasing/decreasing) based on his/her choice of either by selecting the choice

**Possible solution (tentative)**
1. Radio button with action implemented
2.  checkbox with button to implement the action

**Comment by alexanderpann** [comment]
Issue moved to https://github.com/levilucio/EARS-CTRL/issues/13.
