### ISSUE TITLE
Behaviour implementations missing or left behind

### ISSUE THREAD

**Issue by davidmpaz** [IETS3/iets3.opensource#142]
Hello,

after pulling latest updates from repo I did start getting these when building my language:

![selection_077](https://user-images.githubusercontent.com/210742/46298673-ee1ab600-c59f-11e8-9ccd-e03fbf5023dc.png)

Could someone take a look and check whether the methods should be removed or the interface added to those concepts? or vice versa.

Many thanks in advance,
David

**Comment by alexanderpann** [comment]
Closing this ticket because it was fixed long ago.
