### ISSUE TITLE
KernelF Statemachine throws an exception when empty line is used

### ISSUE THREAD

**Issue by AlexeiQ** [IETS3/iets3.opensource#148]
`org.iets3.core.expr.statemachines/StateMachine` throws the following exception, when an empty line is used, eg. between states. This happens probably because that empty line concept `EmptySMC` implements a subconcept of `IValidNamedConcept` without satisfying its constraints.

![image](https://user-images.githubusercontent.com/5792623/48499197-27e60a00-e838-11e8-8456-9e4e963c48bd.png)

**Comment by coolya** [comment]
You can now transfer issues between repositories. That keeps the discussion and timeline intact.

**Comment by alexanderpann** [comment]
Closing because it was fixed in [9fe88be](https://github.com/IETS3/iets3.opensource/commit/9fe88bea7b55841cefe94565515409d7c83455c1).
