### ISSUE TITLE
KernelF SM: Add intention to squash entry/exit-actions

### ISSUE THREAD

**Issue by AlexeiQ** [IETS3/iets3.opensource#149]
KernelF Statemachine states can have multiple entry- or exit-actions. A new intention should enable the user to easily squash multiple entry/exit-actions into one entry/exit-action utilizing a blockexpression.

**Comment by alexanderpann** [comment]
Closing because it was implemented in [2df0418](https://github.com/IETS3/iets3.opensource/commit/2df0418c091600217f9dd4deba524dcfa859d556).
