### ISSUE TITLE
Type inference of box types incorrect

### ISSUE THREAD

**Issue by krishnanm86** [IETS3/iets3.opensource#170]
Context: Initialize a box type into a val, 
val globalcounter = box(10)

Now, the type of globalcounter is locked to number(10) implying any update operation throws a type system error

globalcounter.update(it + 1)

throws the error number(11) (inferred as the type of it+1 is) is not a subtype of number(10)

**Comment by lhartl** [comment]
I feel like for the box types it is a bit different since. In principal, KernelF works with immutables. With box approach we add the possibility to change the value of a val. For me, it feels really weird that incrementing the value by one results in a typesystem error.

**Comment by markusvoelter** [comment]
I think Wladi's comment is accurate. Maybe we can add a warning when using a box this way that suggests to add an explicit type.

**Comment by lhartl** [comment]
👍
