### ISSUE TITLE
A RecordDeclaration should probably contains only RecordMembers not IRecordMembers

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#22]
In a certain project we have our implementation of IRecordDeclaration with its own members (implementing IRecordMember). Now these special members can be used in RecordDeclarations because RecordDeclaration accept as children IRecordMember. Probably it would make sense to restrict the members to RecordMember.

**Comment by markusvoelter** [comment]
![screen shot 2017-01-05 at 17 08 47](https://cloud.githubusercontent.com/assets/592330/21687460/aa65b628-d369-11e6-9f48-b549d930c84b.png)
