### ISSUE TITLE
Type Inference on Nested Lists does not work properly.

### ISSUE THREAD

**Issue by bj2015** [IETS3/iets3.opensource#232]
When inferring the type of a nested inhomogeneous list like `list(5, "foo", list(1))` one seems to get one of the results `list<number>`, `list<string>` or `list<list<number>>` depending on the order of elements in the list and nondeterministically. This is wrong for 3 reasons

1. The type of a list should be independent of the order of its elements,
2. all of the above results are incorrect as they miss 2 out of 3 element types, and
3. type inference should be deterministic.

What would be expected:
I would expect the type of above list to be `list<join<number, string, list<number>>>` and the types of any other permutation of elements to be equivalent to it. I would furthermore expect this to always be the case and not to change after Invalidate Caches.

**Comment by alexanderpann** [comment]
This was fixed in I believe #662 and works now.
