### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#25]
I have run `./gradlew check` several times and sometimes I get 0 failures, some other times I get 2 failures

![screen shot 2017-03-13 at 09 22 51](https://cloud.githubusercontent.com/assets/439078/23846667/ca6ca3de-07ce-11e7-83f8-28322059b949.png)

I cannot see something obviously wrong with those tests

**Comment by alexanderpann** [comment]
Closing this ticket because it is obsolete.
