### ISSUE TITLE
Issue with Inputing max value within the first row of intervals (min/max) the Table Language Instance

### ISSUE THREAD

**Issue by saadbinabid1** [IETS3/iets3.opensource#27]
At present when we start populating the table intervals (both min/max) the max value is underlined and marked red. This only happens to the first row of the table only. This is needs to be sorted out.

**Comment by alexanderpann** [comment]
Closing because it seems to be fixed in commits [5121ac2](https://github.com/IETS3/iets3.opensource/commit/5121ac2aacbefa37dc0cc779614ba225c2d328f2) and [4de524f](https://github.com/IETS3/iets3.opensource/commit/4de524f2ba0e72ab48c62bca124595d61e6add5a).
