### ISSUE TITLE
scoping for ModelProperty concepts in org.iets3.flow.property.formulae does not work

### ISSUE THREAD

**Issue by levilucio** [IETS3/iets3.opensource#28]
The scoping of AtomicProperties should only be restricted to concepts of type ModelProperty (from language org.iets3.flow.property). Now the references are to any concept in the repository.

**Comment by salman2135** [comment]
There are several problems:

1. The reference scoping includes by default the module dependencies even when the scoping is  set to null.
2. model.module.getLanguages and model.module.usedDevkits returns size 0 even when languages and devkits are present. 

A question will be posted in forum to resolve this problems in future.
