### ISSUE TITLE
Comparing postive value with negative in diehl table intervals

### ISSUE THREAD

**Issue by saadbinabid1** [IETS3/iets3.opensource#29]
The problem arises when there is an interval values like we want to input values like To: 5 and From:-6 and constraints are unable to check for 5>-6 (5 greater then -6). We can only check for values that are either both positive or both negative (-5>-6) or (6<5) at present. This should be fixed for the intervals (i.e., both increasing and decreasing)

**Comment by alexanderpann** [comment]
Issue moved to https://github.com/levilucio/EARS-CTRL/issues/6.
