### ISSUE TITLE
Move Error-Highlightning of IcanRunCheckManually form type-interference-rule to checking-rule

### ISSUE THREAD

**Issue by dbinkele** [IETS3/iets3.opensource#301]
Attaching errors and warnings of a ICanRunCheckManually does not work anymore correctly in MPS2019.2. The root cause could be that for attaching the errors to targetNodes a type-checking-rule is responsible. This is not triggered reliable anymore. Therefore this behavior is moved to a checking rule.

**Comment by wsafonov** [comment]
@dbinkele is there something left to do here? Looks like the rule was already refactored as discussed.

**Comment by dbinkele** [comment]
#531 fixes this

**Comment by dbinkele** [comment]
Has been fixed and merged.
