### ISSUE TITLE
CastExpression should consider the number of digits

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#31]
For example casting to `number{1}` the value `3.1234567` should produce `3.1`

**Comment by ftomassetti** [comment]
This is not trivial to do because we need to consider also typedefs, which are defined in toplevel while the cast is defined in base (so it is unaware of typedefs).

For now I have written these tests:

![screen shot 2017-04-03 at 14 09 39](https://cloud.githubusercontent.com/assets/439078/24608543/4181cfc2-1877-11e7-884f-10e91bce9f00.png)

**Comment by ftomassetti** [comment]
I could add a new method on `Type` that takes a value and the original type associated to the value and perform the cast, so the cast expression would be unaware of typedefs. However this would mean having interpretation logic on the type instead than in the interpreter.

Any better idea for this?

**Comment by ftomassetti** [comment]
An alternative could be defining the interpreter for the CastExpression to handle only numbers and override it in the language defining typedefs

**Comment by markusvoelter** [comment]
I looked into this. However, this is not so simple. 

First of all, right now, casting *never* actually changes the value. It
only checks if the value is valid for the type. For numbers, a higher precision
is ok. 

I could override casting for numbers; by adding a specialized interpreter,
this works nicely in a modular way. However, it is not clear which mode I 
should use for changing the precision: truncate, round, etc. And I cannot
specify that in cast<>(), there is no syntax for it. 

So I think you will have to (continue to) use the cast expression together
with the precision expression, as shown in the attached test case.

<img width="574" alt="screen shot 2017-04-10 at 09 13 18" src="https://cloud.githubusercontent.com/assets/592330/24850347/f0bd6688-1dcf-11e7-9dfa-f2cbf87dd9af.png">

**Comment by ftomassetti** [comment]
Ok, for using the precision expression but I am not sure an higher precision is Ok: if a value has an associated type with precision 1, seeing 2 or more decimal digits could be surprising.

**Comment by markusvoelter** [comment]
I don't have a strong opinion there, but it currently works how other people told me it should work. So, I won't change it for now, unless I get more "pressure" from others as well.

**Comment by ftomassetti** [comment]
Understood, thank you for looking into this. I will think about it a little bit more and consider overriding the behavior in the language based on IETS3.
