### ISSUE TITLE
EnumLiterals typesystem does not recalculate types

### ISSUE THREAD

**Issue by lhartl** [IETS3/iets3.opensource#314]
Functioncalls are used in the inferenceRule of EnumLiterals. Therefore types are not recalculated when changing the EnumType. 
Introducing a dependency (there is some statement in the typesystem for this) should solve this.

**Comment by alexanderpann** [comment]
The functional call just asks for the parent node (EnumDeclaration).
So I could add this statement to the start of the inference rule: addDependency(el.parent);
Before I add such as statement, I want to see an example when the types are not recalculated.

**Comment by alexanderpann** [comment]
Not reproducible. Probably some issue with the type system that was fixed in MPS itself.
I've changed the enum literals and then the type and vice versa, and everything works.

**Comment by alexanderpann** [comment]
I close this ticket as not reproducible. The typesystem implementation in MPS also changed quite a bit.
