### ISSUE TITLE
Renaming this project

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#326]
This project is sometimes referred to as "IETS3", sometimes as "KernelF". I find it a bit confusing and maybe this does not help on the marketing side.
What about renaming it KernelF?

**Comment by markusvoelter** [comment]
That's not feasible because there's other stuff in this project too. If anything, we should factor KernelF out into a separate repo. But we don't have the time. We're thinking about at least providing a separate download/artifact.

**Comment by wsafonov** [comment]
@markusvoelter can you open a new ticket and briefly describe, what parts we want to publish separately? If there are no strong technical blockers, splitting up current single iets3.opensource publication should not be a big problem
