### ISSUE TITLE
constraints for attribute copy in the flow language

### ISSUE THREAD

**Issue by levilucio** [IETS3/iets3.opensource#33]
In the scripts written using flow language we need to say not only which attributes need to be copied over when models are potentially created, but also to put some conditions on the copy. This can be achieved by adding arbitrary constraints on the copy using an expression language. This could be done using Markus' expression language.

**Comment by alexanderpann** [comment]
Issue moved to https://github.com/levilucio/EARS-CTRL/issues/7.
