### ISSUE TITLE
migration suspended: iets3.core.xxxx can't be loaded

### ISSUE THREAD

**Issue by toaruShiro** [IETS3/iets3.opensource#345]
Hey guys,

    I'm a beginner of MPS and wanted to import a new project into MPS 2019.3, but problems with the iet3 related dependencies occurred so I tried to follow the doc to use gradlew build. Then I got:

> Task :buildLanguages FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':buildLanguages'.
> Process 'command 'E:\program\java\java11\installSpace\bin\java'' finished with non-zero exit value 1

    Could anobody help me with it?

![3XZ5`H$S3N9FT%%530))SY5](https://user-images.githubusercontent.com/60000739/76569540-52101080-64ee-11ea-9d9e-c020c7b4832b.png)

![image](https://user-images.githubusercontent.com/60000739/76569614-7f5cbe80-64ee-11ea-9b01-a3c0d739f682.png)

**Comment by wsafonov** [comment]
Hi,
as for the "Migration suspended" dialog, you need to run `gradlew setup` first before opening the project in MPS to provision it with all required language dependencies.

As for the build issue, can you try to re-run it with `--stacktrace` option and provide the full error with a stacktrace? I assume you face a well-known issue with the command line length limitation on Windows.

**Comment by toaruShiro** [comment]
> Hi,
> as for the "Migration suspended" dialog, you need to run `gradlew setup` first before opening the project in MPS to provision it with all required language dependencies.
> 
> As for the build issue, can you try to re-run it with `--stacktrace` option and provide the full error with a stacktrace? I assume you face a well-known issue with the command line length limitation on Windows.

Hi,
    Thank you so much for your reply. I was inspired by the length you mentioned so I changed the address of workspace to make the url shorter, it worked. However, after my executing gradlew setup and open the project in WPS the problem still occurs. Does the relative address between iets3 and workspace matter, or should I do some more operations?

![image](https://user-images.githubusercontent.com/60000739/76574837-6a852880-64f8-11ea-85b7-5d9b038162d5.png)

![image](https://user-images.githubusercontent.com/60000739/76574906-a15b3e80-64f8-11ea-87ef-e6cc55fb04a8.png)

![image](https://user-images.githubusercontent.com/60000739/76575114-3eb67280-64f9-11ea-8540-097b0f75103a.png)

**Comment by alexanderpann** [comment]
Closing because the mentioned issues might not occur anymore in recent versions of this repository.
