### ISSUE TITLE
List equals operation yields typesystem error if temporal language is imported

### ISSUE THREAD

**Issue by wsafonov** [IETS3/iets3.opensource#353]
See `ListEquality` in tests: http://127.0.0.1:63320/node?ref=r%3A75f6a9e9-cf21-495f-b1aa-7fd992d0d7d0%28test.ts.expr.os.m1%40tests%29%2F871690368833936470

If we import `org.iets3.core.expr.temporal` language, list equals operations have a typesystem error:
![image](https://user-images.githubusercontent.com/8157816/77581880-c67b8400-6ede-11ea-943f-2957e1501e93.png)

**Comment by alexanderpann** [comment]
It is unclear what changed but in recent MPS versions, this issue is not reproducible.
