### ISSUE TITLE
Create additional math-expressions

### ISSUE THREAD

**Issue by MLanghammer** [IETS3/iets3.opensource#360]
Additionally to the existing math expressions, like the ProductExpression and the SumExpression, we need to create (at least) the following expressions:

IntegralExpression
CosinusExpression
SinusExpression
...

Besides of the obvious editor-support, we need to write an interpreter for these expressions and make sure that they either work together correctly with units, or issue a typesystem error if they cannot deal with units at all.
Notes:

* in order to create the interpreter correctly, we can use the Apache.Math functions, which support the above mentioned mathematical operations. 
* one of the MPS examples and also mbeddr already contains an IntegralExpression/an integral editor, from which we can reuse the presentation.

**Comment by markusvoelter** [comment]
I am working on the trigonometric stuff for the ATLAS project.

**Comment by wsafonov** [comment]
@markusvoelter I've just realized there is already some work done by @dbinkele in #363. As we need to review this anyway, can you have a look there and tell me if it (still) makes sense to put your work on top of that PR (if actually needed)?

**Comment by alexanderpann** [comment]
Closing because the additional math expressions were implemented in https://github.com/IETS3/iets3.opensource/pull/363.
