### ISSUE TITLE
When defining a constant I can refer to the constant itself

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#37]
I am not using the most recent version of IETS3, so I am not sure this issue is still present.

I think we should prevent this from happening.

![screen shot 2017-04-20 at 09 26 16](https://cloud.githubusercontent.com/assets/439078/25218544/73b4878c-25ab-11e7-972d-aa26a278a4fa.png)

**Comment by ftomassetti** [comment]
I can also have this issue indirectly
![screen shot 2017-04-20 at 09 32 46](https://cloud.githubusercontent.com/assets/439078/25218780/6491baf8-25ac-11e7-8089-c437928bd36d.png)

I would consider letting val definitions to see only preceeding definitions, otherwise it can become difficult to identify these cycles.

Also, these cycles prevent the typesystem to calculate the type.

**Comment by markusvoelter** [comment]
Fixed on master, also including indirect cycles. Based on ICycleDetector.

**Comment by ftomassetti** [comment]
Great!
