### ISSUE TITLE
AbstractMinMaxExpression forces result to be a subtype of real

### ISSUE THREAD

**Issue by bkolb** [IETS3/iets3.opensource#371]
I have a custom type, similar to a tuple containing multiple numbers.

I would want to use the min/max expression on it (with a custom interpreter). Currently this is not possible because the TS rule forces the result to be a real type

**Comment by alexanderpann** [comment]
Inference rules can be overridden in extending languages since 2021.3.3, so this issue is obsolete (see: https://youtrack.jetbrains.com/issue/MPS-35414/Support-overriding-typesystem-checking-rules-from-extending-languages).
