### ISSUE TITLE
Triggering checks based on localized changes 

### ISSUE THREAD

**Issue by saadbinabid1** [IETS3/iets3.opensource#38]
The main idea is to trigger the property based on the localized changes made during composition of the model. In the initial attempt, there will be an appropriate change listener added to the model. The change listener will  listen to the nodes of the concepts. The output will be a model-based change management system that will minimize the property execution for the flow dashboard.

**Comment by alexanderpann** [comment]
Issue moved to https://github.com/levilucio/EARS-CTRL/issues/16.
