### ISSUE TITLE
NixHandling in KernelF

### ISSUE THREAD

**Issue by markusvoelter** [IETS3/iets3.opensource#380]
## Internal representation of nix

The interpreter works with objects. A null value constitutes an error, so we cannot represent nix as null. Instead, current users represent nix as a particular type such as NixRuntimeValue or something. One extension in the framework would be to define an interface `INixValue` that would be implemented by all such representations.

This would allow the interpreter to treat it generically, for example in the case of `if cond then` when `cond` evaluates to `INixValue`.

## Syntax for dealing with nix

A couple of built in operations are probably useful:

* `someVal.hasValue` returns true if the value is not nix * `someVal.isNix` the opposite * `allHaveValue(v1, v2, v3)` same as `hasValue` but for multiple; used as guard with `if` * 'nix' expression that returns an 'INixValue'; which runtime type is instantiated should be configurable with extension point

## Data only

There are two different ways how nix is used. In one case, nix is just another value that can propagate through an expression evaluation tree. For example, if you multiply `count * price` and `count` is nix, then the result of the expression might be nix as well (or zero, depending on your semantics, but it might be nix).

In the other case nix is only allowed when accessing something that represents storage. The expression that accesses this storage will immediately replace nix with some kind of default value, such as zero for numbers that evaluate to nix. In this case, nix is never the result of an evaluation of a computation, only when looking directly at data. You still need the operations proposed above, but the rest of the interpreter is much simpler. In this sense, the second option is preferable. But nicks is never preserved, So this option is also much more limited.

The second option requires no special support in KernelF, since it does not have any native support for accessing storage (unless we reinterpret records this way). Everything would happen in the interpreters of extensions.

The former case brings us to the handling of nix throughout the interpreter.

## Handling of nix

It turns out that different KernelF users want the interpreter to behave differently if it encounters nix. The above nix-as-false is common, but it is not so clear what happens if the user wants to execute `nix + 5` or `sqrt(nix)`.

This could be made configurable. However, this would mean that everywhere in the interpreter we would have to check if an argument is nix and call a call back / extension point. I think this is too expensive, considering that the interpreter is already relatively slow. So I suggest that we do not implement this behavior in the framework and continue to require users to override the interpreters for those language concepts that might encounter nix.

We should probably provide a default implementation that is reasonable that users can optionally use. We can just pick one of the implementations used by clients.

## Relationship to Option Types

Technically, there is no relationship. The whole point of the discussion here is that it would make the type system unaware of the fact that something might be nix (or none, in option type parlance). Since our business users don't care about that (and option types are too verbose and cumbersome for them) I would probably just remove them completely.

**Comment by markusvoelter** [comment]
One more problem: there are a few places internally to KernelF where option types are used, for example in `list<T>.first`. If we were to remove option types, what do we do? We'd of course type it as `T`, but at runtime? 
* We can either directly stop the interpreter with a something akin to a constraint error
* or we can return `nix`

I prefer the following, because I think using `nix` value should be optional, so we can't make it part of an internal API.

**Comment by alexanderpann** [comment]
Closing because this feature was implemented a while ago.
