### ISSUE TITLE
FunctionArgument does not recognize colon

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#384]
This test has been failing since upgrading from MPS 2019.2 to MPS 2020.1.2

<img width="858" alt="Screenshot 2020-07-13 at 14 50 11" src="https://user-images.githubusercontent.com/439078/87306466-5a1da280-c518-11ea-9550-f7e67d0c0580.png">

What happens is that when typing the name of the parameter (e.g., `p1`) as a type `:` this used to be recognized as the separator between parameter name anda parameter type. This is not the case anymore as you can see below:

<img width="678" alt="Screenshot 2020-07-13 at 14 53 13" src="https://user-images.githubusercontent.com/439078/87306640-9bae4d80-c518-11ea-839b-4da4ffb0d375.png">

**Comment by wsafonov** [comment]
Have you already tested with the latest version of MPS-extensions from the last week? There is an issue with optional cells that has been fixed by a workaround in this PR: JetBrains/MPS-extensions/pull/304

**Comment by ftomassetti** [comment]
In this project we are using the mbeddr platform but not MPS extensions. We are using the latest version available (2020.1.22359.74347fd)

**Comment by wsafonov** [comment]
MPS-extensions is always packaged together with mbeddr platform. That version is correct, but iets3.opensource has not yet been migrated. I have executed the migration on branch `bugfix/grammarcells-optional-issue`. Please try out with the latest build from that branch: https://build.mbeddr.com/buildConfiguration/Iets3_BuildOrgIets3core?branch=bugfix%2Fgrammarcells-optional-issue&buildTypeTab=overview&mode=builds&focusLine=0

**Comment by ftomassetti** [comment]
> MPS-extensions is always packaged together with mbeddr platform. That version is correct, but iets3.opensource has not yet been migrated

I have looked at the pom of iets3 opensource from yesterday and it seems it has a dependency on MPS 2020.1.2 so I thought it was migrated https://projects.itemis.de/nexus/content/repositories/OS/org/iets3/opensource/2020.1.4524.8b0d822/opensource-2020.1.4524.8b0d822.pom but also on friday it seems it was already depending on MPS 2020.1.2 https://projects.itemis.de/nexus/content/repositories/OS/org/iets3/opensource/2020.1.4522.8b0d822/opensource-2020.1.4522.8b0d822.pom

I have then tried setting the dependencies to:
```
ext.mpsVersion = '2020.1.2'
ext.mbeddrVersion = '2020.1.22359.74347fd'
ext.iets3OpensourceVersion = 'bugfix-grammarcells-optional-issue.2020.1.4525.cfd21eb'
```

This seems to solve the issue, at least when trying this into MPS and run an editor test in MPS which used to fail. I will check also on the build server. I see an error about the tracing language being disposed but I saw that occur also before.

**Comment by wsafonov** [comment]
> ...so I thought it was migrated

Actually I meant here the workaround migration from MPS-extensions, not the migration from MPS itself - sorry, it was a bit confusing.

Then I would consider this as resolved and merge the changes into master.

**Comment by ftomassetti** [comment]
Yes, I would agree that this should be closed as the patch hit master (or the MPS version specific branch)
