### ISSUE TITLE
Problem when entering the first literal in an enum

### ISSUE THREAD

**Issue by kbirken** [IETS3/iets3.opensource#419]
When entering the first literal in an enum and trying to move on to the next one (e.g., by pressing Enter or `,`), content-assist will show up and present three entries:

<img width="393" alt="image" src="https://user-images.githubusercontent.com/1193045/100453228-e93be900-30ba-11eb-8627-92d36c99a720.png">

Expected: content-assist shouldn't show up at all, the first literal should be accepted as entered and it should look like this:

<img width="216" alt="image" src="https://user-images.githubusercontent.com/1193045/100453468-3d46cd80-30bb-11eb-957c-e72a4576edbc.png">

**Comment by wsafonov** [comment]
I have also recently bumped into this behaviour. This is because of the grammar wrap cell used in both branches of an alternation editor. But I remember there was some workaround for this. @slisson what would you say?
