### ISSUE TITLE
Decouple specific runtime JDK version for CL builds from local JDK version

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#435]
**Problem/Drawback**
In the current state, developers are required to either have JDK 11 installed or configured to be able to perform a CL build of _iets.opensource_. See: https://github.com/IETS3/iets3.opensource/blob/master/build.gradle#L27

Due to the fact that JDK 11 is only required for the CL build it is often cumbersome (especially on windows) to switch to the required JDK version for "just" building the project from sources. 

**Improvement**
It would be great to loose this restriction for the CL build to allow building iets.opensource with any JDK supported by gradle (1.8+). To do so, the following would be required:

- [ ] download the required JDK via gradle for CL build
- [ ] set downoaded JDK as required JDK_HOME for build
- [ ] set JDK for MPS generated Ant files for tests

Notes:
- [ ] This should also be done for iets3.core

**Comment by coolya** [comment]
The mps-gradle-plugin got you covered: https://github.com/mbeddr/mps-gradle-plugin#download-jetbrains-runtime

**Comment by alexanderpann** [comment]
This was done long ago.
