### ISSUE TITLE
Multi-Dispatch/Poly Framework. 

### ISSUE THREAD

**Issue by markusvoelter** [IETS3/iets3.opensource#48]
Takes precond into account
fail expr in func w/o effect before it

**Comment by arimer** [comment]
@markusvoelter is there any need to keep that issue? 
I dont undertand what it means and why to keep it. In case it is required, do you mind adding a discription?

**Comment by alexanderpann** [comment]
Follow-up question: Are we talking about a language like [de.q60.mps.polymorphicfunctions](http://mbeddr.com/mps-platform-docs/aspects/polyfun/) but for KernelF and not Base language?

**Comment by arimer** [comment]
No further input available. Therefore closing for now.
