### ISSUE TITLE
Shortcut for "Run manually" doesn't work if root node is a ICanRunCheckManually

### ISSUE THREAD

**Issue by kbirken** [IETS3/iets3.opensource#480]
The `RunManually` infrastructure provides three actions for running the check on a node, a root node and a container, respectively. The keymap `runEval` ([nodeURL](http://127.0.0.1:63320/node?ref=r%3Acdcdec44-a636-42c8-b599-c146eb2ca77d%28org.iets3.core.plugin.plugin%29%2F4816256765116125442)) assignes the same shortcut to each of them, and the `isApplicable` methods decide which one will be executed. 

However this logic overlaps for nodes and root nodes, such that if a root node is itself a `ICanRunCheckManually`, no check will be executed (as the root node will be checked first if the shortcut is hit, but its `execute` method doesn't find itself as ancestor. 

Expected: If the shortcut is hit, the `runManuallyOnNode` action should be triggered.

**Comment by alexanderpann** [comment]
Closing because it was fixed in https://github.com/IETS3/iets3.opensource/pull/481 and follup commits.
