### ISSUE TITLE
Bugfix: Omit Double Messages

### ISSUE THREAD

**Issue by dbinkele** [IETS3/iets3.opensource#490]

**Comment by dbinkele** [comment]
Ensure that in http://127.0.0.1:63320/node?ref=r%3Ad354209e-0bea-497f-b905-d66f72900fa8%28org.iets3.analysis.base.plugin%29%2F7137735640367500827 
bufferd messages are not doubled.

**Comment by alexanderpann** [comment]
Closing because it was fixed in #489.
