### ISSUE TITLE
The type inference underlying the alt-expressions doesn't work correctly

### ISSUE THREAD

**Issue by kbirken** [IETS3/iets3.opensource#505]
The type inference of the alt-expression doesn't work as expected. Two examples:

<img width="628" alt="image" src="https://user-images.githubusercontent.com/1193045/127029537-21740ca5-3c55-44c8-a139-1f40530afa41.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/1193045/127029656-3fbcce08-e868-49ca-b18e-5fcd4d13e3fe.png">

Expected: The result should be a join-type (but I didn't find a specification for this in the KernelF-paper). 

Gimmick: It would be nice if the underlying infrastructure (`TypingHelper`) would support an option to return just a single type and issue errors if the list of input expressions contains different types.

**Comment by kbirken** [comment]
The DecTab and some other KernelF constructs suffer from the same problems.

**Comment by lhartl** [comment]
[JoinType](url)

**Comment by lhartl** [comment]
@kbirken can you list the problematic parts of kernelF when you stumble over them please? I think these are nice tickets for people to pick up during ttt.

**Comment by heikob2** [comment]
#### Observations
The Problem is located in the `SimpleTypesPrimitiveTypeMapper::computerSupertype()` in the _toplevel-else-block_:
- There the jetbrains _SubtypingManager_ `SubtypingManagerNew` calls `leastCommonSupertypes()`, which returns an empty set if **2 different types** are provided and the correct **join** is returned as type.
- If there are **3 different types** provided an arbitrary type is returned (cause the parameter is a hash-set). The result then is the **wrong type**, which is exposed.

#### Todos
- [ ] fix it
- [ ] ensure that the types in the join-type are distinct

**Comment by mgronover** [comment]
I choose fixing it by using the following  work around:

The least common super type of a set of types is determined by the method:
`typechecker.getSubTypingManager().leastCommonSupertypes(setOfTypes, boolStrongSubtyping)`

If `setOfTypes` contains the three iets3 types : `{StringType, BooleanType, NumberType}` , the derivation of the least common super type is done wrong. It operates correctly if there are only two types (as mentioned [above](https://github.com/IETS3/iets3.opensource/issues/505#issuecomment-889278536)). So I broke the set down and called that function repeatedly until the least common type was determined.

Additionally I recursively flattened the join types and optional types before using this set of types to get the super type of them. If there was an option type (or a NoneType is one of the types within the set) this will result into an surrounded option type.

**Comment by kbirken** [comment]
@mgronover Just tested this in order to close the ticket. The join-types are now computed nicely and contain what they are expected to, even if there are more than two types.

However, there is an additional (maybe academic) question: I would expect that two types `join<[a, b]>' and `join<[b, a]>' are semantically equal (the least common supertype of `a` and `b` does not depend on the order of the two types). So maybe the types in a join-type should be sorted according to some criterion. On the other hand, it seems that the join-type cannot be used explicitly in KernelF anyway (see `IJoinTypeContext` prohibiting this), and I also didn't find a way to compare two types. So the issue probably not relevant and can be ignored for now.

Just in case, here is a slightly more elaborate example (the types of the two functions are join types with the same contained types, but in different order):

<img width="249" alt="image" src="https://github.com/IETS3/iets3.opensource/assets/1193045/2a17e865-3dd8-4358-949d-1562ebf10c42">

**Comment by mgronover** [comment]
@kbirken you are absolutely right this fix should also be done.
