### ISSUE TITLE
Implementing Java or custom text generator in KernelF 

### ISSUE THREAD

**Issue by markoercegovac** [IETS3/iets3.opensource#526]
Hello, I need help with Java generator in KernelF. I was able to run a test interpreter in KernelF, but I dont know how to start or implement code/text generator in KernelF. Does anyone know how to do it or have some examples of implementing code/text generator for KernelF in MPS Tool? Thanks in advance..

**Comment by wsafonov** [comment]
Hi @markoercegovac, we provide a KernelF-to-Java generator included in the KernelF distribution. Actually, there was a question about it asked in the public Slack channel for IETS3: https://jetbrains-mps.slack.com/archives/CBM449YG5/p1632169499006900. There you can ask any further questions that you might have regarding the existing Java generator.
