### ISSUE TITLE
create devkit per plugin

### ISSUE THREAD

**Issue by coolya** [IETS3/iets3.opensource#54]
We are missing some devkits for better organising our devkits so that they relate to the plugin.

**Comment by arimer** [comment]
Not sure what this excatly meant. At the moment I see some devkits which are mostly realted to the generator implementation.

<img width="449" alt="grafik" src="https://github.com/IETS3/iets3.opensource/assets/16648247/5083772a-6d46-4292-af6c-41ee3734db35">

We can have a closer look in case we need a more fine grain distribution.

**Comment by alexanderpann** [comment]
Let's close the ticket. It might not reflect the current state anymore. We have also recently introduced new devkits.
