### ISSUE TITLE
MPS requires restart after adding simpleTypes language to get editor to work

### ISSUE THREAD

**Issue by RobertWalterU3d** [IETS3/iets3.opensource#544]
When I use KernelF's `Expression` concept in a child-role feature and want to be able to create a `NumberLiteral` in the sandbox model, I need to restart MPS first in order to have NumberLiteral in the scope.

Also see this conversation: https://jetbrains-mps.slack.com/archives/CBM449YG5/p1628698242016300

**Comment by alexanderpann** [comment]
SimpleTypes is implemented as an [extension point](https://www.jetbrains.com/help/mps/extension-support.html#extensionlanguage). When you add the language, the extension doesn't get automatically registered, only when MPS is started. There are 3 options:
1. restart MPS
2. import one of the [devkits](https://github.com/IETS3/iets3.opensource/tree/master/code/languages/org.iets3.opensource/devkits) (for example org.iets3.core.expr.core.devkit) which included the expression language + simpleTypes
3. execute the action "Reload all classes".

Number 2 would be the preferred option.

**Comment by alexanderpann** [comment]
Unfortunately, option 2 only works if you didn't allready import the language. In this case, only option 1 and 3 is possible. When you create a new model and want to use KernelF, import the Devkit. As a result, simpleTypes will be automatically loaded.

**Comment by RobertWalterU3d** [comment]
Understood.
I wonder if this could be improved somehow, cause for users without extensive knowledge of the implementation details this is hard too impossible to discover. 
Could a check on model-level be written that informs the user when they add a imports the simple language that it is recommended to add the devkits instead, or to restart MPS/reload all classes to ensure the extension point being registered correctly?
