### ISSUE TITLE
Migrate 'Override basetype() in Collectiontype' to 2021.1

### ISSUE THREAD

**Issue by dbinkele** [IETS3/iets3.opensource#550]
in maintenance/MPS20203. the method 'basetype()' in 'Collectiontype' has been overriden. This changed the behavior drastically, as now the basetype is returned instead of CollectionType. 

P.S. This cause 57 tests in iets3.core (maintenance/MPS2020.3) to fail, which is now fixed. In order to fix this also in master (2021.1). the current change has to be made.

**Comment by wsafonov** [comment]
Change is already in master.
