### ISSUE TITLE
Validation rule missing for CollectionRangeSpec

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#56]
![grafik](https://user-images.githubusercontent.com/16648247/28624871-d20c52a4-721a-11e7-90ee-ebcea23e50c0.png)

The rule should complain that min > max.

**Comment by markusvoelter** [comment]
So the range is correctly checked for numbers, right? What you are referring to is the size spec of the list?

**Comment by markusvoelter** [comment]
I have fixed this on my current branch. Cherry-pick this commit e598eef to get it on master.
