### ISSUE TITLE
type in enum declarations can't be set anymore

### ISSUE THREAD

**Issue by lhartl** [IETS3/iets3.opensource#576]
In an enum declaration it used to be possible to add a type by typing a < after the name. This doesn't work anymore. There is also no intention for this.

Example:

<img width="443" alt="Screenshot 2022-06-29 at 08 47 18" src="https://user-images.githubusercontent.com/30237070/176370028-ca70cd87-18e9-4676-887e-18f5166f7fc9.png">

most likely this is due to the fix in grammar cells (I did not investigate though)

**Comment by alexanderpann** [comment]
I should probably check all editors with optional cells. This is the third issue of this nature.

**Comment by lhartl** [comment]
Yes, it would be great if you would finde time to check all the editors. Since this is a problem, that customers are facing already, could you please fix this one quickly? I'd take care of reviewing and merging the PR

**Comment by alexanderpann** [comment]
Sure.

**Comment by lhartl** [comment]
Thank you!!!
