### ISSUE TITLE
Provide mechanism to hide nodes in the editor, but delegate the hide logic to other level

### ISSUE THREAD

**Issue by mfsoliveira** [IETS3/iets3.opensource#614]
The visualization of nodes in editors may depend on some logic that is implemented outside the language definition. 
By providing some interface, the hiding logic can be delegated to other layers but tested in the concept editor where the language is defined.

Use case: 
The preview of nodes in editors may depend on the availability of those nodes according to the selection status in a variability model.
Unselected nodes could be hidden, reducing the cognitive load during artifact analysis.

**Comment by alexanderpann** [comment]
Some thoughts about this if I understand it correctly: for the filter of ref node list cells, querylist and the show if style item you can access the `editorContext` variable, and you might be able to make the filtering depend on `editorContext.getSelectedNodes()` if it should depend, for example, on the selected nodes in the editor. You can of course just access the model through the `node` variable for other information like the selection status of different nodes for other use cases. For hiding nodes in general without using the show if style item, you could create a node attribute that hides the editor by default. Whenever you want to hide a node, you just have to attach this annotation to the node, and it won't be visible anymore.
For other cases, you still have the possibility to overwrite an editor with the conditional editor language from MPS-extensions. Isn't this enough?

**Comment by dbinkele** [comment]
Temporarily the ICanHide-Interface has been added to a feature branch of iets3.core and looks like this: 
![image](https://user-images.githubusercontent.com/50654800/200284146-dd131641-af54-4515-8412-153b06909cd6.png)
