### ISSUE TITLE
Breaking change in EnumLiterals associated value

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#615]
This summer has been introduced I change (I think in this commit https://github.com/IETS3/iets3.opensource/commit/9302cc810e667b4db1e8fad6d678cd2799072cfd by @alexanderpann ) to values associated to EnumLiterals, preventing to associate the same value to more than one literal.

For example, this test would fail with the current implementation of IETS3 while it used to pass:
<img width="591" alt="Screenshot 2022-10-18 at 15 38 18" src="https://user-images.githubusercontent.com/439078/196447080-7ddf8563-4a81-41aa-bc13-67d46f0a930e.png">

We have actually used enums in this way for years, and for our use-cases this is actually useful.

Would you reconsider going back to the previous behavior?
Alternatively, would it be possible to disable it by using some flag on enum?

I would be happy to provide a PR for this, in case this can be useful

**Comment by ftomassetti** [comment]
I have seen the PR fixing this was closed but not merged. Is there anything I can do to help?
Also, would it be possible to have it merged in the MPS 2021.1 maintenance branch?

**Comment by alexanderpann** [comment]
We were not sure if we should go back to the old behavior (A) or make it customizable (B), that's why I deleted my PR for option A because we went with option B. The PR is for the maintenance branch.

**Comment by ftomassetti** [comment]
I would prefer the old way, as I feel the keys should be unique but not necessarily the old values

**Comment by alexanderpann** [comment]
We already went with B so that's why there is now an extension point called `typesystemCustomization` that can be implemented to get back to the old behavior.

**Comment by ftomassetti** [comment]
Great, thank you!

**Comment by alexanderpann** [comment]
I am closing because the issue was resolved.
