### ISSUE TITLE
Create IRestrictAdvancedStuff

### ISSUE THREAD

**Issue by sergej-koscejev** [IETS3/iets3.opensource#62]
Create an interface (ideally with a better name than in the issue title) that would have a bunch of `allowFeatureXyz()` methods. Intentions such as "wrap in opt<...>" would check if the root implements `IRestrictAdvancedStuff` and if it does, and `allowOptions()` returns `false`, the intentions would disable themselves.

This would help hide IETS3 features that our particular project doesn't use, to confuse our users less.

**Comment by markusvoelter** [comment]
So the same for attempt things and casting.

**Comment by markusvoelter** [comment]
I will do this next week when I have merged the tracing to master.

**Comment by markusvoelter** [comment]
Check out IControlAdvancedFeatures in core.expr.base
