### ISSUE TITLE
Add support for the Darcula theme for all languages

### ISSUE THREAD

**Issue by alexanderpann** [IETS3/iets3.opensource#636]
- There is currently the open PR https://github.com/IETS3/iets3.opensource/pull/625
- There was also a merged PR a long time ago: https://github.com/IETS3/iets3.opensource/pull/311

I can see 254 occurences of the Color class currently in IETS3. Most of them should be changed to use JBColor ([more info](http://mbeddr.com/mps-platform-docs/patterns/user_experience/?h=darcula#dark-theme)). Testing should be done with the Darcula theme. Many UI related things are already fixed in MPS-Extensions: https://github.com/JetBrains/MPS-extensions/pull/512

**Comment by HeikoBecker** [comment]
Solved with #638
