### ISSUE TITLE
Possible rounding error in  SumOP interpreter

### ISSUE THREAD

**Issue by alexanderpann** [IETS3/iets3.opensource#639]
The interpreter works with double and should work with BigDecimal.
The CollectionHelper should also be moved to a solutution that can be used for the interpreter and generator. The interpreter shouldn't depend on this class which is currently located in one of the genjava models.

**Comment by HeikoBecker** [comment]
@apann I am closing this issue as the corresponding PR has been merged. Please reopen if this was wrong.
