### ISSUE TITLE
[EARS-CTRL] get rid of the duplicate library loading issue

### ISSUE THREAD

**Issue by levilucio** [IETS3/iets3.opensource#65]
We need to test for the Simulink library already being loaded to avoid the exception. 

Some hints:

https://stackoverflow.com/questions/1139386/check-if-a-dll-library-is-already-loaded-java/1139433#1139433

https://stackoverflow.com/questions/1030792/dll-already-loaded-in-another-classloader

**Comment by alexanderpann** [comment]
Issue moved to https://github.com/levilucio/EARS-CTRL/issues/3.
