### ISSUE TITLE
[EARS-CTRL] generating test cases does not always reset the state to all actuators being "off"

### ISSUE THREAD

**Issue by levilucio** [IETS3/iets3.opensource#66]
<img width="880" alt="screen shot 2017-08-18 at 13 28 38" src="https://user-images.githubusercontent.com/9036388/29457176-2e3b561e-8419-11e7-90d1-4060d5de5049.png">

In the example, the state of the actuators is carried from the first to the second test case when it shouldn't.

**Comment by alexanderpann** [comment]
Issue moved to https://github.com/levilucio/EARS-CTRL/issues/2.
