### ISSUE TITLE
Mutable: Update currency check in box update target uses wrong equality check

### ISSUE THREAD

**Issue by alexanderpann** [IETS3/iets3.opensource#701]
The following expression will fail although the old value (12) is equal to the expected value (12).

```
fun f/RM(b: box<number>) { 
  val x = b.val 
  b.update(12) 
  b.update from (12) to (x + 1) 
}
```

[Here](http://127.0.0.1:63320/node?ref=r%3Afbe318af-2afe-4858-8d66-a206b7f47bc8%28org.iets3.core.expr.mutable.interpreter.plugin%29%2F3487973603071619826) should be an not `equals` check instead of `!=`.

**Comment by arimer** [comment]
Fixed by #997
