### ISSUE TITLE
Broken/Wrong Icons

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#74]
For some concepts: RequirementsChunk, UserDirectory they icons seems to be broken or wrongly rendered.
![image](https://user-images.githubusercontent.com/16648247/31491665-57e41a32-af48-11e7-9619-5cf99e05e511.png)
![image](https://user-images.githubusercontent.com/16648247/31491687-67a2e944-af48-11e7-946e-bbefd474f803.png)

**Comment by alexanderpann** [comment]
Closing this ticket because the old icons are not used anymore and this issue is obsolete. All current icons are rendered correctly.
