### ISSUE TITLE
`InfHelper.equals` not working as expected

### ISSUE THREAD

**Issue by alamqadem** [IETS3/iets3.opensource#761]
The method returns the wrong result for the following cases: 0.0 and 0 or -0 and 0.
Example with the Console:
```java
> {
    #print InfHelper.equals("0", "0");
    #print "\n";
    #print InfHelper.equals("0", "0.0");
    #print "\n";
    #print InfHelper.equals("0", "-0");
    #print "\n";
  }
  true
  false
  false
```

It shouldn't do string comparison, but numerical one like `greatOrEquals`.

**Comment by arimer** [comment]
Should be closed by https://github.com/IETS3/iets3.opensource/pull/762. 
@alamqadem could you please verify and re-open in case the bug is still there?

**Comment by alamqadem** [comment]
> Should be fixed by #762. @alamqadem could you please verify and re-open in case the bug is still there?

I just pulled `maintenance/mps20222` and it's not working.
![image](https://github.com/IETS3/iets3.opensource/assets/10254994/df4adb31-5352-49be-b96a-ab8b4d7d27eb)

**Comment by arimer** [comment]
@alamqadem it was merged on 20213, so I guess some cascading merges are missing.

**Comment by arimer** [comment]
@alamqadem which iets3 versions are you using atm. where that bug should be fixed?

**Comment by alamqadem** [comment]
> @alamqadem which iets3 versions are you using atm. where that bug should be fixed?

We just need it for MPS2022.2

**Comment by arimer** [comment]
A fix is now merged to `maintenance/mps20222`. Feel free to try it out and to close the issue.

**Comment by alamqadem** [comment]
> A fix is now merged to `maintenance/mps20222`. Feel free to try it out and to close the issue.

It works now, thanks 🙂
