### ISSUE TITLE
"gramm" should be "g" in SIUnitsDerivedAndScaled KernelF library

### ISSUE THREAD

**Issue by eugenschindler** [IETS3/iets3.opensource#768]
In the mentioned library, which is shipped with IETS3.opensource, "gramm" is used for what is normally defined in SI by "g". It is also like this for all prefixes:
![image](https://github.com/IETS3/iets3.opensource/assets/6429350/2c9e3cde-c33d-4946-8ed2-4b940b900912)

Please consider changing all of these instances to the more customary "g", "kg", etc. for the unit.
The relevant node info for the library in question:
module:  org.iets3.core.expr.typetags.units.si
model:   org.iets3.core.expr.typetags.units.si.units
root:    SIUnitsDerivedAndScaled [Library]
node:    ngramm [Unit]
url:     http://127.0.0.1:63320/node?ref=r%3A1881124b-7ac4-4b0f-a7dd-12953ac3263b%28org.iets3.core.expr.typetags.units.si.units%29%2F7092451331179160040

**Comment by alexanderpann** [comment]
Seems like someone used the German term by accident. When we rework the unit language, will have built-in support for metric prefixes anyway, which should help with such issues.

**Comment by arimer** [comment]
closed by #795
