### ISSUE TITLE
Remove write access in async running if Solverfacade

### ISSUE THREAD

**Issue by dbinkele** [IETS3/iets3.opensource#778]
https://youtrack.jetbrains.com/issue/MPS-36395

Currently we generate a SolverTask by calling a generator facade from a checking rule.
It was necessary to use a 'write-access'. This is not reasonable as the  generator facade does only write on transient models.
The ticket https://youtrack.jetbrains.com/issue/MPS-36395 fixes this bug, such that we can remove the write access in 

http://127.0.0.1:63320/node?ref=r%3Ad354209e-0bea-497f-b905-d66f72900fa8%28org.iets3.analysis.base.plugin%29%2F4386560887386140284

**Comment by arimer** [comment]
Could you please add the corresponding MPS version via label, where this bug appears?

**Comment by alexanderpann** [comment]
According to the comment, https://github.com/IETS3/iets3.opensource/pull/1023 also fixed this issue.
