### ISSUE TITLE
Using list types in conditional expressions (if, alt) results into compiler failures not fetched by tests

### ISSUE THREAD

**Issue by mgronover** [IETS3/iets3.opensource#786]
I wrote some code as an example, that currently is not able to be successful generated to Java:

![image](https://github.com/IETS3/iets3.opensource/assets/38247916/4207baa9-2dbc-4457-aaff-11e724a5e4ac)

Rebuilding it results in warning issues:

![image](https://github.com/IETS3/iets3.opensource/assets/38247916/1544ade1-f763-4bde-bfd7-7b4e0cb6957f)

and the generated source is not compilable at all:
![image](https://github.com/IETS3/iets3.opensource/assets/38247916/6e409339-6e3e-49c4-a7ed-b21e8bff855c)

But now it is getting even worse:

When I switch to ` KernelF Tests: Generator` and `KernelF Tests: Generator (workspace)` and trigger the test to be executed.....

"WOW", I get all test green:
![image](https://github.com/IETS3/iets3.opensource/assets/38247916/95b5f6b6-6811-4d7a-8ce2-c9f22df8b4ca)

That's not what the way it should be!

If you wanna try out:
https://github.com/IETS3/iets3.opensource/tree/bugfix/MeetTypeCreationOnFunctionGeneration

**Comment by mgronover** [comment]
I suppose we require a suitable test environment to check if some domain spec. code can be successful translated (generated **and** compiled) into something executable (without warnings from the typesystem, the generator or compiler) .

**Comment by mgronover** [comment]
Here they are:
![image](https://github.com/IETS3/iets3.opensource/assets/38247916/3357870d-491a-4651-95ba-3fd7838cb0df)

**Comment by arimer** [comment]
@mgronover can we close this one due to the merge in #790 ?

**Comment by mgronover** [comment]
Yes, we can.
