### ISSUE TITLE
Typing in an operator after a LogicalNotExpression results in creating a child expression inside instead of outside the LogicalNotOperator

### ISSUE THREAD

**Issue by stephaneberle9** [IETS3/iets3.opensource#81]
Steps to reproduce:
- Type a negated boolean expression: '!myBool'
- Type in an boolean operator behind like this: '!myBool &&'

Expected result: '!myBool && <no expression>'
Actual result: '!(myBool && <no expression>)'

**Comment by alexanderpann** [comment]
Cannot reproduce. Seems to be fixed.
