### ISSUE TITLE
IComponentsChunkContent implements IDocumentbale

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#84]
Not sure this is a good idea. Because `EmptyComponentsChunkContent `also implements `IDocumentbale `.

**Comment by alexanderpann** [comment]
Closing because documentation can't be added to concepts implementing `IEmpty`, so this is probably not an issue anymore. There is also the method `isDocumentationAllowed` for other cases where documentation shouldn't be allowed.
