### ISSUE TITLE
Allow simple realization of IKindSpecificAttributes

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#85]
### Idea:
Currently there is no interface a language developer may use, to realize own attributes which should be applicable in a special component kind.

### What should be done:
-interface should provide a constraint that can inherited
-attributes shouldbe visible in a specific IContextTypeProvider or on an element of a specific kind

**Comment by alexanderpann** [comment]
Closing this ticket because this feature seems to be implemented in https://github.com/IETS3/iets3.opensource/commit/977ea0d9c844aebf6dadbcb7b382b905c9cf64b1. @arimer feel free to reopen if this feature isn't finished.
