### ISSUE TITLE
Relax naming constraint from IOptionallyNamed

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#88]
Currently the naming constraint of IValidNamedConcept is used in IOptionallyNamed and is really restrictiv:

![grafik](https://user-images.githubusercontent.com/16648247/33126815-3c11613a-cf86-11e7-8ca2-ff15a2a75fb4.png)

In customer projects naming constraints are always different then the one form the iets3. Overriding this constraint on downstream projects is really hard and triggers the creation of a subconcept for every IOptionallyNamedConcept. Creating a subconcept just for overriding a naming constraints is a no-go. 

I would propose to relax this constraint by removing: 
`propertyValue.matches("[a-zA-Z$[_]][a-zA-Z0-9$[_']]*")`

**Comment by arimer** [comment]
Hi @bj2015,
I saw that you adapted this constraint last time at fc37b832. Can you maybe comment why?

**Comment by bj2015** [comment]
The variable names in SolverTasks implement IValidNamedConcept. I wanted to allow names like x'.

However, when someone lets a Concept of his language implement IValidNamedConcept than he trusts that above restrictions are adhered to. In my case, for example, I have to encode all characters that can appear in variable names, but are not allowed in the SMTLIB language. When the restriction would be removed I would have to come up with some scheme howto encode arbitrary characters.
In general, when removing the restriction one would have to carefully review all concepts implementing the interface in order to ensure that this does not break anything.

I would hence suggest to simply add another Interface that does the same as IValidNamedConcept, but handles the propertyValue more liberally - or even allows specifying a custom regex.

**Comment by arimer** [comment]
One less invasive solution might be, to create a new Interface and to override the method : `allowEverythingExceptWhitespace()` to return `true`. Then `IOptionallyNamed` could use the new interface and the restriction would be relaxed.

**Comment by coolya** [comment]
Can we get a list of constrains that implement  `IOptionallyNamed` but not `IValidNamedConcept`.

**Comment by arimer** [comment]
To find out if some  `IOptionallyNamed ` has their own constraints ?

**Comment by coolya** [comment]
No to find out which concept would be affected by this change.

**Comment by bj2015** [comment]
`IValidNamedConcept` as it currently exists is complete nonsense from an architectural perspective. It offers 3 different restrictions (NonIdentifierNames, EverythingExceptWhitespace, default) for the property name which can be selected by overriding the two methods `allowNonIdentifierNames` and `allowEverythingExceptWhitespace`.

A much cleaner solution would be as follows:
1. create a new concept (maybe named `IRestrictMyName`) which has an abstract method `isValidName(string name): boolean` which implements the restriction.
2. create a number of interfaces that inherit from `IRestrictMyName` and implement the method `isValidName()` in different ways. For instance `IAllowEverythingExceptWhitespaceInMyName`, `IAllowTheUsualSpecialCharsInMyName`, etc.
3. Make all Concepts that currently implement `IValidNamedConcept` instead implement that interface that best matches their previous restriction.

In this way everyone can implement arbitrary Name restrictions simply by letting their concept implement `IRestrictMyName` and implementing the method `isValidName()` appropriately. Common Restrictions can still be turned into reusable Interfaces.

What do you think?

**Comment by coolya** [comment]
Why would we want to introduce such concept that does nothing than delegate from the constrain to that method? How is this better than simply writing your own constrains directly in the constrains aspect of your language? 

If we want to enable composition of constrains than we should look for a solution for that. We had discussion two days ago about how interfaces were _abused_ to reuse constrains and compose them. I think we all agree that mutiinheritance is not a good solution because of the unexpected (and most probably undefined) behaviour you can get with it. I think we should focus this discussion on whenever `IOptionallyNamed` should be a specialisation of `IValidNamedConcept` which I think it should not.

But given the fact that we have shipped this behaviour and we don't necessarily have all the code that relies on it under our control we should seek a solution that is backward compatible.

As I have seen concepts implementing both interfaces (`IValidNamedConcept` *and* `IOptionallyNamed `) explicitly I wanted to get some information about how common this is. Because I personally never thought that `IOptionallyNamed` specialises `IOptionallyNamed`. Maybe it wasn't obvious to others as well. These concepts would not be affected by the proposed change because they still get the constrains from their explicit implementation of `IValidNamedConcept`. Another metric to measure the impact would be so check how many concepts that implement `IOptionallyNamed` actually override methods defined in `IValidNamedConcept`. 

I would really like to avoid breaking everybodies constrains by recklessly changing such a central interface.

**Comment by bj2015** [comment]
Would it be possible for a migration script to find all concepts that implement IValidNamedConcept and replace this dependency by a concept constraint?

**Comment by coolya** [comment]
I think so, the migration could then remove the "implements" clause from the projects. Writing the migration might be a bit tricky but should still be possible.

**Comment by bj2015** [comment]
Swell, so we have a way out of this mess!

When I understood correctly, `IValidNamedConcept` has no reason for existence, since
a) It does not make sense to apply the same restrictions to all names, and
b) using an interface concept to encapsulate a particular restriction introduces unneccessary coupling between all its usages which causes problems when one of them wants to change it later. It should hence be considered bad style and discouraged. Furthermore, it offers no advantage over using the constraints aspect to introduce the restriction.

Hence, the cleanest solution would be to stop using IValidNamedConcept and replace all its usages with direct constraints in order to get rid of the unneccessary coupling. And since we do not have all code using it under our control, doing that with a migration script would be the proper (and only) way.

**Comment by arimer** [comment]
Some overview regarding the current implementation  in IETS3: 
The lists are showing the current **direct implements relationship** to : 
`IOptionallyNamed && !IValidNamedConcept `
`!IOptionallyNamed && IValidNamedConcept `
 `IOptionallyNamed && IValidNamedConcept `

### Concepts implementing direct IO but not VN
<a href="http://127.0.0.1:63320/node?ref=r%3Ab3786745-c763-4a49-a754-f84e15236f18%28org.iets3.components.core.structure%29%2F7804632404593841020">Port</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ab3786745-c763-4a49-a754-f84e15236f18%28org.iets3.components.core.structure%29%2F3432899422388046302">AbstractComponentInstance</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A66e07cb4-a4b0-4bf3-a36d-5e9ed1ff1bd3%28org.iets3.core.expr.base.structure%29%2F2807135271608145920">SomeExpression</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A66e07cb4-a4b0-4bf3-a36d-5e9ed1ff1bd3%28org.iets3.core.expr.base.structure%29%2F6481804410367226920">TryExpression</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aba7faab6-2b80-43d5-8b95-0c440665312c%28org.iets3.core.expr.tests.structure%29%2F8219602584783477664">AbstractTestItem</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A9e305a48-41d6-450d-b02f-7d9ad145eac2%28org.iets3.components.functional.structure%29%2F409503520737353753">Member</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A9e305a48-41d6-450d-b02f-7d9ad145eac2%28org.iets3.components.functional.structure%29%2F4952752849913616601">MessageArgument</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A6399195b-f53f-4d2f-9194-153d6bba843f%28org.iets3.components.hardware.structure%29%2F5002195738791686650">BusInstance</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aef9bb98e-a93f-4192-82c7-eb0ac4ced2c8%28org.iets3.datalog.structure%29%2F2410118052903118801">Query</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aef9bb98e-a93f-4192-82c7-eb0ac4ced2c8%28org.iets3.datalog.structure%29%2F7882845195679611101">DeclarationVarRef</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A528978db-f668-4cbc-9011-11a7adedeae1%28org.iets3.protocol.transport.structure%29%2F571807164490501645">ProtocolMap</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A104106fc-b2da-4088-837a-7eff364d1d21%28org.iets3.vlan.structure%29%2F760266716710712853">VlanContainerRef</a>


### Concepts implementing direct VN but not IO
<a href="http://127.0.0.1:63320/node?ref=r%3A7f8b53fb-2dfc-4e51-940a-0573ffa4389c%28org.iets3.glossary.structure%29%2F7551038907536067158">GlossaryChunk</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A7f8b53fb-2dfc-4e51-940a-0573ffa4389c%28org.iets3.glossary.structure%29%2F7551038907536067159">GlossaryTerm</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A82415404-e5c7-47c8-ae5b-951fc882e316%28org.iets3.req.core.structure%29%2F5151426049053136302">AbstractRequirement</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ab3786745-c763-4a49-a754-f84e15236f18%28org.iets3.components.core.structure%29%2F7804632404593231361">Component</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ab3786745-c763-4a49-a754-f84e15236f18%28org.iets3.components.core.structure%29%2F8434481698271949569">Variable</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ac1f7e681-4373-4429-b23f-337a1dd93658%28org.iets3.core.users.structure%29%2F8479184967780604356">User</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ac1f7e681-4373-4429-b23f-337a1dd93658%28org.iets3.core.users.structure%29%2F8479184967780604478">UserDirectory</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A66e07cb4-a4b0-4bf3-a36d-5e9ed1ff1bd3%28org.iets3.core.expr.base.structure%29%2F1919538606559981270">ErrorLiteral</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A142b83fd-ec1c-45fe-a1a4-55a13210bd7b%28org.iets3.core.expr.repl.structure%29%2F1240669143552786952">REPL</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aaf0af2e7-f7e1-4536-83b5-6bf010d4afd2%28org.iets3.core.expr.lambda.structure%29%2F4790956042241053102">ValExpression</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ada65683e-ff6f-430d-ab68-32a77df72c93%28org.iets3.core.expr.toplevel.structure%29%2F7061117989422575313">EnumLiteral</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A854255a4-0f76-4555-8c94-d91e2ad4eb02%28org.iets3.core.expr.statemachines.structure%29%2F195141004743991572">StatemachineVar</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A4df5de9d-c793-4b8c-9d89-32508bcd7b9c%28org.iets3.analysis.solversupport.structure%29%2F5233708286811794622">VarDecl</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A4df5de9d-c793-4b8c-9d89-32508bcd7b9c%28org.iets3.analysis.solversupport.structure%29%2F5205359464215372105">SolverEnumLit</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A9e305a48-41d6-450d-b02f-7d9ad145eac2%28org.iets3.components.functional.structure%29%2F6171685075657610245">Operation</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A9e305a48-41d6-450d-b02f-7d9ad145eac2%28org.iets3.components.functional.structure%29%2F6171685075660810486">ProtocolState</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A9e305a48-41d6-450d-b02f-7d9ad145eac2%28org.iets3.components.functional.structure%29%2F6171685075660810492">ProtocolVariable</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A9e305a48-41d6-450d-b02f-7d9ad145eac2%28org.iets3.components.functional.structure%29%2F4062862969282228701">LocalException</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A9e305a48-41d6-450d-b02f-7d9ad145eac2%28org.iets3.components.functional.structure%29%2F1019070541443734096">ConstantParameter</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A9e305a48-41d6-450d-b02f-7d9ad145eac2%28org.iets3.components.functional.structure%29%2F7547431020114907695">CallResultVar</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ac53b8bbc-6142-4787-a6e4-66310b772b37%28org.iets3.core.expr.math.structure%29%2F4944417823362115312">MathLoopExpr</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aef9bb98e-a93f-4192-82c7-eb0ac4ced2c8%28org.iets3.datalog.structure%29%2F4805125377352945147">AtomDeclaration</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aef9bb98e-a93f-4192-82c7-eb0ac4ced2c8%28org.iets3.datalog.structure%29%2F2479124081000108808">LocalVarDecl</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aa7e2f963-3e46-49e0-a385-e8c7f33c91b7%28org.iets3.featuremodel.structure%29%2F3989254429233029649">FeatureModel</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aa7e2f963-3e46-49e0-a385-e8c7f33c91b7%28org.iets3.featuremodel.structure%29%2F3989254429233062247">AbstractFeature</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aa7e2f963-3e46-49e0-a385-e8c7f33c91b7%28org.iets3.featuremodel.structure%29%2F8997672845436117511">FeatureAttribute</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A506f9888-5dfa-47b9-b3ef-bc082381808a%28org.iets3.functiontree.structure%29%2F1866843961903532411">FunctionTreeRoot</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A506f9888-5dfa-47b9-b3ef-bc082381808a%28org.iets3.functiontree.structure%29%2F1866843961903533928">FunctionTreeNode</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A538ff6f8-a4c2-44e9-934f-5743d1d6933b%28org.iets3.hardware.structure%29%2F6209909044671247389">ResourceInterface</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A27239e6c-2946-42bb-870c-503af3ba0c23%28org.iets3.safety.structure%29%2F4536991857487799059">CustomFailureModeSpec</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A27239e6c-2946-42bb-870c-503af3ba0c23%28org.iets3.safety.structure%29%2F4536991857487799064">InternalFailureMode</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A6372c12c-334e-48d7-bb02-00fde2e38029%28org.iets3.simbench.marker.structure%29%2F3574570262832019103">TraceImportConfiguration</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ad54e664f-b231-4cba-98ed-8dd5e2586400%28org.iets3.simbench.structure%29%2F5019312492394871289">Step</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ad54e664f-b231-4cba-98ed-8dd5e2586400%28org.iets3.simbench.structure%29%2F5019312492394988771">System</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ad54e664f-b231-4cba-98ed-8dd5e2586400%28org.iets3.simbench.structure%29%2F5019312492394988985">Partitioning</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ad54e664f-b231-4cba-98ed-8dd5e2586400%28org.iets3.simbench.structure%29%2F5019312492395129683">Scenario</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ad54e664f-b231-4cba-98ed-8dd5e2586400%28org.iets3.simbench.structure%29%2F5019312492395129841">UseCase</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ad54e664f-b231-4cba-98ed-8dd5e2586400%28org.iets3.simbench.structure%29%2F3222414152510186819">SimTrigger</a>

### Concepts implementing direct VN and IO
NONE

### Interfaces extending direct IO but not VN
NONE

### Interfaces extending direct VN but not IO
<a href="http://127.0.0.1:63320/node?ref=r%3Ab3786745-c763-4a49-a754-f84e15236f18%28org.iets3.components.core.structure%29%2F7804632404593342035">IComponentsChunkContent</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A657c9fde-2f36-4e61-ae17-20f02b8630ad%28org.iets3.core.base.structure%29%2F7804632404594256696">ISpecRoot</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A657c9fde-2f36-4e61-ae17-20f02b8630ad%28org.iets3.core.base.structure%29%2F229512757698888199">IOptionallyNamed</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aa6074908-e483-4c8e-80b5-5dbf8b24df4c%28org.iets3.core.expr.path.structure%29%2F7814222126785170970">IMember</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aaf0af2e7-f7e1-4536-83b5-6bf010d4afd2%28org.iets3.core.expr.lambda.structure%29%2F7554398283340318473">IArgument</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Aaf0af2e7-f7e1-4536-83b5-6bf010d4afd2%28org.iets3.core.expr.lambda.structure%29%2F4790956042240100911">IFunctionLike</a>
<a href="http://127.0.0.1:63320/node?ref=r%3Ada65683e-ff6f-430d-ab68-32a77df72c93%28org.iets3.core.expr.toplevel.structure%29%2F2861782275883475449">IToplevelExprContent</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A854255a4-0f76-4555-8c94-d91e2ad4eb02%28org.iets3.core.expr.statemachines.structure%29%2F8735085014268479230">ISMContent</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A1eb914ff-b91c-4cbc-93c6-3ecde7821894%28org.iets3.core.expr.typetags.units.structure%29%2F8337440621611270350">IUnit</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A37b80d61-d147-495a-8ada-2fe53e290387%28org.iets3.franca.structure%29%2F4128077259236968892">IFrancaName</a>
<a href="http://127.0.0.1:63320/node?ref=r%3A538ff6f8-a4c2-44e9-934f-5743d1d6933b%28org.iets3.hardware.structure%29%2F6654311517970972527">IHardwareChunkContent</a>


### Interfaces extending direct VN and IO
NONE


The list tansitiv implements/extends dependencies of concepts and interfaces to both interfaces is currently missing though.

**Comment by bj2015** [comment]
Thanks, @arimer .

One point I forgot to mention explicitly: Interface concepts extending `IValidNamedConcept` should of course be treated just like concepts implementing it.

That said, I think we can regard / treat `IOptionallyNamed` just like any other concept/interface implementing/extending `IValidNamedConcept`.

**Comment by bj2015** [comment]
Correction: Thinking about it some more, applying the migration script would remove `IValidNamedConcept`, but install `IOptionallyNamed` as a new central restriction-carrying hub.

While I don't think we should remove `IOptionallyNamed`, we should definitely avoid implementing the name restriction in such a central place.

Hence the migration script would have to move the name restriction to all concepts that implement an interface that transitively extends `IValidNamedConcept`. In the code under our control, this would be:

<a href="http://127.0.0.1:63320/node?ref=r%3A657c9fde-2f36-4e61-ae17-20f02b8630ad%28org.iets3.core.base.structure%29%2F229512757699383348">IValidNamedConcept</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3Ab3786745-c763-4a49-a754-f84e15236f18%28org.iets3.components.core.structure%29%2F7804632404593342035">IComponentsChunkContent</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3A657c9fde-2f36-4e61-ae17-20f02b8630ad%28org.iets3.core.base.structure%29%2F7804632404594256696">ISpecRoot</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3A657c9fde-2f36-4e61-ae17-20f02b8630ad%28org.iets3.core.base.structure%29%2F229512757698888199">IOptionallyNamed</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3Aa6074908-e483-4c8e-80b5-5dbf8b24df4c%28org.iets3.core.expr.path.structure%29%2F7814222126785170970">IMember</a>
  * <a href="http://127.0.0.1:63320/node?ref=r%3Ada65683e-ff6f-430d-ab68-32a77df72c93%28org.iets3.core.expr.toplevel.structure%29%2F602952467876375079">IRecordMember</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3Aaf0af2e7-f7e1-4536-83b5-6bf010d4afd2%28org.iets3.core.expr.lambda.structure%29%2F7554398283340318473">IArgument</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3Aaf0af2e7-f7e1-4536-83b5-6bf010d4afd2%28org.iets3.core.expr.lambda.structure%29%2F4790956042240100911">IFunctionLike</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3Ada65683e-ff6f-430d-ab68-32a77df72c93%28org.iets3.core.expr.toplevel.structure%29%2F2861782275883475449">IToplevelExprContent</a>
  * <a href="http://127.0.0.1:63320/node?ref=r%3Ada65683e-ff6f-430d-ab68-32a77df72c93%28org.iets3.core.expr.toplevel.structure%29%2F602952467877559919">IRecordDeclaration</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3A854255a4-0f76-4555-8c94-d91e2ad4eb02%28org.iets3.core.expr.statemachines.structure%29%2F8735085014268479230">ISMContent</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3A1eb914ff-b91c-4cbc-93c6-3ecde7821894%28org.iets3.core.expr.typetags.units.structure%29%2F8337440621611270350">IUnit</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3A37b80d61-d147-495a-8ada-2fe53e290387%28org.iets3.franca.structure%29%2F4128077259236968892">IFrancaName</a>
* <a href="http://127.0.0.1:63320/node?ref=r%3A538ff6f8-a4c2-44e9-934f-5743d1d6933b%28org.iets3.hardware.structure%29%2F6654311517970972527">IHardwareChunkContent</a>
  * <a href="http://127.0.0.1:63320/node?ref=r%3A538ff6f8-a4c2-44e9-934f-5743d1d6933b%28org.iets3.hardware.structure%29%2F6577518218813835392">IResource</a>

**Comment by arimer** [comment]
The IValidNamedConcept offers now more static virtual methods to relax the naming constraints. Therefor from my point of view the issue can be closed.
