### ISSUE TITLE
Using methods on list types having list types as a result causes compilation errors (javac).

### ISSUE THREAD

**Issue by mgronover** [IETS3/iets3.opensource#888]
The compilation of some of the following test function fails (root node: [functionType](http://127.0.0.1:63320/node?ref=r%3Af9a70877-66f3-464b-86cb-67a9d543be8c%28test.in.expr.os.functions%40tests%29%2F728017840040128456) ) :
![image](https://github.com/IETS3/iets3.opensource/assets/38247916/89ab7a34-7802-4627-90ac-f3a213b27a5d)

Here are the error messages
![image](https://github.com/IETS3/iets3.opensource/assets/38247916/7258369b-5450-427d-bbd1-98f222cc1c9f)

**Comment by arimer** [comment]
Fixed by https://github.com/IETS3/iets3.opensource/pull/889
