### ISSUE TITLE
Document ConstraintAndError

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#9]
It is not obvious what it does and how to use `buildErrorMessage`. Should we use to check if there is an error and `null` means everything is fine?

**Comment by alexanderpann** [comment]
Closing because the class has changed significantly over the last years. An example default implementation can be found in [DefaultConstraintAnderror](http://127.0.0.1:63320/node?ref=r%3A83e946de-2a7f-4a4c-b3c9-4f671aa7f2db%28org.iets3.core.expr.base.behavior%29%2F8219602584775848527).
