### ISSUE TITLE
Numbers and subtyping

### ISSUE THREAD

**Issue by ftomassetti** [IETS3/iets3.opensource#92]
I have this test:
![screen shot 2017-11-28 at 10 08 21](https://user-images.githubusercontent.com/439078/33311140-230c20d8-d424-11e7-9155-0b3edead50c5.png)
![screen shot 2017-11-28 at 10 08 31](https://user-images.githubusercontent.com/439078/33311147-26735db8-d424-11e7-9932-49660364d33c.png)
In practice an integer constant is not consider to be a subtype of a number with infinite precision, while a number with one decimal is consider to be a subtype of a number with infinite precision.
I would suggest it is a bit surprising.
What do you think? Should I look into writing a PR to change that or this behavior is intended?

**Comment by markusvoelter** [comment]
I think this makes sense, yes.

**Comment by ftomassetti** [comment]
Thank you, PR #93 submitted
