### ISSUE TITLE
Generator: Compilation error when an alternative or if expression uses list types

### ISSUE THREAD

**Issue by mgronover** [IETS3/iets3.opensource#956]
These four functions produces compilation errors due to invalid Java code (tested in MPS2021.3 and also in MPS2022.2):

![image](https://github.com/IETS3/iets3.opensource/assets/38247916/9a671152-097b-4088-b98c-a91698489743)

The generated code of the second one is:

![image](https://github.com/IETS3/iets3.opensource/assets/38247916/54025d2e-acbb-4577-9e2f-9c05a07e591c)

And the error message that occurs when compiling:

![image](https://github.com/IETS3/iets3.opensource/assets/38247916/b9d4dab9-baa7-4163-bf69-e2bc86a29b32)

**Comment by arimer** [comment]
Fixed with #957
