### ISSUE TITLE
IntroduceReveal and showEffect intentions should be possible to hide

### ISSUE THREAD

**Issue by joao-silveira** [IETS3/iets3.opensource#96]
Currently we have two intentions built in opensource:

`showEffect`
http://127.0.0.1:63320/node?ref=r%3A7d06857c-251f-4454-ac9c-c398e5200a04%28org.iets3.core.expr.base.intentions%29%2F5096753237477078750

`IntroduceReveal`
http://127.0.0.1:63320/node?ref=r%3A7d06857c-251f-4454-ac9c-c398e5200a04%28org.iets3.core.expr.base.intentions%29%2F4934857995792118313

That I have no use for in my custom projects and therefore would like to hide or remove them.

Is it possible that they are no longer required and can be removed?

Or maybe we could make use of the `IControlAdvancedFeatures` interface?

**Comment by markusvoelter** [comment]
Handled via IControlAdvancedFeatures
