### ISSUE TITLE
org.iets3.core.expr.typetags.physunits.IUnit should manage required access to Quantities

### ISSUE THREAD

**Issue by arimer** [IETS3/iets3.opensource#983]
At the moment we have only a way to access the [specification](http://127.0.0.1:63320/node?ref=r%3A720d563d-1633-46b3-a98e-08d2fde4c4a8%28org.iets3.core.expr.typetags.physunits.behavior%29%2F2034036099106762165) via this interface. It would be required to also access [Quantity](http://127.0.0.1:63320/node?ref=r%3A4f64e2f0-6a4e-4db3-b3bf-7977f44949b6%28org.iets3.core.expr.typetags.physunits.structure%29%2F2034036099103723290) available in the sub concept.

**Comment by arimer** [comment]
@alexanderpann at the moment [Quantity](http://127.0.0.1:63320/node?ref=r%3A4f64e2f0-6a4e-4db3-b3bf-7977f44949b6%28org.iets3.core.expr.typetags.physunits.structure%29%2F2034036099103723287) does not have any interface/abtract concept, is this fine for the time beeing or should we introduce on? 

I would like to add a behaviour method, to [IUnit](http://127.0.0.1:63320/node?ref=r%3A720d563d-1633-46b3-a98e-08d2fde4c4a8%28org.iets3.core.expr.typetags.physunits.behavior%29%2F5629679905544223785) that would allow me to access the [quantity](http://127.0.0.1:63320/node?ref=r%3A4f64e2f0-6a4e-4db3-b3bf-7977f44949b6%28org.iets3.core.expr.typetags.physunits.structure%29%2F2034036099103723290) of the subconcept.

**Comment by alexanderpann** [comment]
I mentioned this somewhere but we should just check how generic IUnit we want the interface to be but the change looks fine.

**Comment by arimer** [comment]
closed with #988
